version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:latest
    ports:
      - "9000:9000"
    volumes:
      - ./front-end/softy-pinko-front-end:/var/www/html/softy-pinko-front-end
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: softy-pinko-backend:latest
    ports:
      - "5252:5252"
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge